### ISSUE TITLE
Add "Keyword" to block for PMPro

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-goals#1]
In core plugin, we use "keywords" when registering the block so that they can all be found both by their "name" and the keyword "pmpro".

Need to add that to the goal block here:
https://github.com/strangerstudios/pmpro-goals/blob/master/js/pmpro-goals-block.js#L47

Like: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/blocks/account-links-section/block.js#L47

**Comment by andrewlimaza** [comment]
Completed with latest commit! :)
