### ISSUE TITLE
Enhancement: Pass $percentage, other details in hooks.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-goals#5]
These hooks would be more useful with the $percentage and maybe $total and $goal passed to them:
https://github.com/strangerstudios/pmpro-goals/blob/d1a72d494219e6ed2c5fb05efcabf8e3ad175788/pmpro-goals.php#L262
https://github.com/strangerstudios/pmpro-goals/blob/d1a72d494219e6ed2c5fb05efcabf8e3ad175788/pmpro-goals.php#L271
https://github.com/strangerstudios/pmpro-goals/blob/d1a72d494219e6ed2c5fb05efcabf8e3ad175788/pmpro-goals.php#L281

**Comment by andrewlimaza** [comment]
Added to 1.1. :)
